### ISSUE TITLE
Диалог открытия/сохранения файлов

### ISSUE THREAD

**Issue by aNNiMON** [TemporaryTeam/NoticEditor#11]
Немного сбивает с толку при открытии/сохранении файлов выставленный фильтр *.txt.*.pdf и т.д.

Допустим, я хочу открыть файл, а в диалоге видны по умолчанию только txt, приходится всегда переключаться на все файлы.

Поэтому предлагаю при открытии файлов выставлять ExtensionFilter в *.txt, *.html, *.json и отдельно All files. 
Сохранение в zip сделать нормально с вводом имени архива (чтоб не бралось имя из корневого элемента, а то я его планирую убрать), при этом ExtensionFilter будет *.zip
Там, где нужно выбрать папку, показывать диалог выбора папок. И так далее для всего остального.

**Comment by NaikSoftware** [comment]
Вроде можно закрывать.

**Comment by aNNiMON** [comment]
@SeTSeR оно б само закрылось при слиянии PR #22 

А закрывать только если проблема решена, а то pull request висит, а issue закрыт :smile_cat:

**Comment by SeTSeR** [comment]
Так PR не сливается

**Comment by aNNiMON** [comment]
@SeTSeR уже сливается :smirk:
