### ISSUE TITLE
Дерево заметок

### ISSUE THREAD

**Issue by aNNiMON** [TemporaryTeam/NoticEditor#13]
В `TreeView` поставить [`setShowRoot(false)`](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/TreeView.html#setShowRoot-boolean-), чтобы убрать видимость корневого элемента.

Контекстное меню добавления ветки/заметки, соответственно пусть будет на всём `TreeView`

И, наконец, убрать привязку с корневого элемента, а то по нему и имя zip-архива ставится и много чего ещё.

**Comment by SeTSeR** [comment]
Собственно, лучше тогда сделать корневым элементом элемент выше
Именно потому что я не смог присобачить меню ко всему TreeView, этого не было, сейчас можно и сделать

**Comment by SeTSeR** [comment]
В общем, вроде бы всё есть

**Comment by aNNiMON** [comment]
А ты проверял? У меня не работает создание ветки/заметки.

**Comment by SeTSeR** [comment]
Да, проверял, всю ночь почти сидел над этим

**Comment by NaikSoftware** [comment]
в EditNoticeTreeCell какая-то жесть.

1. Зачем писать ```if (source.equals(controller.getAddBranchItem()))``` ? Разве ```==``` недостаточно? 

2. ```getNoticeTreeItem() ``` дергается милион раз в одном и том же методе

3. Толи копипаста, толи незнаю что, но ```String content = getNoticeTreeItem().getNotice().getContent();``` при создании категории ненужно (и не используется). Зато вызывает Нулпоинтер если сразу при запуске ни один с элементов не выделен и попробовать создать категорию.

**Comment by aNNiMON** [comment]
@NaikSoftware ты прав. 

1. Контекстное меню лучше обрабатывать отдельно, а не всё в одном методе. То есть `handleAddBranch`, `handleAddNotice`, `handleDelete`.

2. Вот там в первой ветке if в `handleContextMenu` вообще непонятно, что происходит. Надо чтоб @SeTSeR объяснил.

3. Fixed.

**Comment by SeTSeR** [comment]
О какой первой ветке идёт речь?

**Comment by NaikSoftware** [comment]
Ее почистил уже @aNNiMON ... и я, у себя параллельно

**Comment by aNNiMON** [comment]
Там где рассчитываются category

**Comment by SeTSeR** [comment]
А что непонятного? Вынес общий код для веток туда, дабы дублирования не было

**Comment by NaikSoftware** [comment]
там условия странные, получалось "если нажали удалить или контент==null" нифига не логично :smiling_imp:

**Comment by SeTSeR** [comment]
Если нажали удалить, то неважно, является ли заметка листом, и удачять её надо из списка детей родителя
Если же заметка - лист, то сыновей у неё нет => оперируем со списком детей родителя

**Comment by NaikSoftware** [comment]
вот это и нужно было написать в коментарии, а то непонятно
