### ISSUE TITLE
Структура проекта непонятная

### ISSUE THREAD

**Issue by NaikSoftware** [TemporaryTeam/NoticEditor#18]
Если EditNoticeTreeCell - это виджет в дереве, который создается системой, а NoticeTreeItem - это данные для элемента в дереве, в доках об этом написано, тогда почему NoticeTreeItem в пакете view, если это model? И NoticeCategory лишний, его функции должен выполнять NoticeTreeitem

**Comment by aNNiMON** [comment]
@NaikSoftware вот именно, тоже говорил Сергею об этом.
Надо бы перенести в model и заодно создать пакет controller, перенести туда контроллеры.
