### ISSUE TITLE
Ненаходимое контекстное меню

### ISSUE THREAD

**Issue by NaikSoftware** [TemporaryTeam/NoticEditor#24]
Я когда только скачал, не мог никак понять как добавить новую заметку в дерево. Нужно как то показывать что оно существует.

Также метод его обработки handleContextMenu в классе редактирования лишний как по мне. Его нужно запихнуть в какой-то контроллер что-ли..

**Comment by SeTSeR** [comment]
Он и так в контроллере. Мне пришлось так сделать, так как не было возможности получить выделенный элемент

**Comment by NaikSoftware** [comment]
Выделенный элемент хранится в контроллере и так под именем ```currentTreeItrm``` кажись.

**Comment by SeTSeR** [comment]
Нет, это открытый лист.

**Comment by NaikSoftware** [comment]
Нет, это итем, который в фокусе, независимо лист или ветка
`currentTreeItem = (NoticeTreeItem) newValue;`
короче я это завтра переделаю, там удалится 4 лишних метода я посмотрел

**Comment by SeTSeR** [comment]
А, это не мой код, вот оно что

**Comment by NaikSoftware** [comment]
Исправлено (вывод справки в тестовой заметке)
