### ISSUE TITLE
Перенести файлы локализации

### ISSUE THREAD

**Issue by aNNiMON** [TemporaryTeam/NoticEditor#38]
Сейчас файлы `*.properties` лежат в  `com/temporaryteam/noticeditor/translate`, нужно перенести их в корневую папку `i18n`.

Вообще, во многих проектах вижу такую структуру:

```
com/.../
font/
fxml/
i18n/
images/
styles/
```

Предлагаю и нам так организовать.

**Comment by SeTSeR** [comment]
Тут есть два варианта: либо мы всё выносим в корень, как предлагаешь ты, либо выносим в корень только resources, а там уже fxml и прочее.

**Comment by aNNiMON** [comment]
@SeTSeR не, пусть уже будет так, как есть. Но переименование остаётся в силе. i18n, locales или bundles.
