### ISSUE TITLE
Баг с добавлением заметки

### ISSUE THREAD

**Issue by NaikSoftware** [TemporaryTeam/NoticEditor#57]
Когда в корне только одни ветки, то невозможно в корне создать заметку. Фокус всегда на одной из веток. Можно решить с пом. drag&drop

**Comment by SeTSeR** [comment]
Токмо это не баг

**Comment by NaikSoftware** [comment]
Фича?

**Comment by aNNiMON** [comment]
Недоработка

**Comment by mrEDitor** [comment]
Предлагаю:
а) всё же показывать корень дерева, возможно, отменяя его сворачивание, как малокостыльный вариант;
б) наставить костылей (достаточно много), чтобы изменить активную область каждого узла на вот такую:
![image](https://cloud.githubusercontent.com/assets/6552749/9413174/f9051426-4838-11e5-96e1-83b8dd051c73.png)
Что думаете?

**Comment by NaikSoftware** [comment]
Предлагаю просто сделать drug&drop 
Он в этой программе и так необходим

**Comment by aNNiMON** [comment]
Согласен с Николаем.

**Comment by mrEDitor** [comment]
Хм, DnD я сделать планировал, но куда дропать, если в дереве нет свободного места?

**Comment by NaikSoftware** [comment]
Да как во всех программах, выводить полосу между элементами/више/ниже чтобы вставить рядом, выделять ветку, чтобы вставить в нее

**Comment by SeTSeR** [comment]
Баг закрывать? В корне создавать заметку уже давно можно
